# Generated by Django 6.0.1 on 2026-01-20 13:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AutomationRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("correlation_id", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("event_type", models.CharField(db_index=True, max_length=100)),
                ("lead_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("webhook_url", models.URLField()),
                ("payload_hash", models.CharField(max_length=64)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("success", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
                ("attempts", models.IntegerField(default=0)),
                ("request_headers", models.JSONField(blank=True, null=True)),
                ("response_body_snippet", models.TextField(blank=True)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("payload_preview", models.JSONField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="automations_event_t_55a57e_idx",
                    ),
                    models.Index(
                        fields=["lead_id", "event_type"],
                        name="automations_lead_id_79e011_idx",
                    ),
                ],
            },
        ),
    ]
