# Generated by Django 6.0.1 on 2026-01-18 14:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("business_name", models.CharField(max_length=200)),
                ("contact_person", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("industry", models.CharField(blank=True, max_length=100)),
                (
                    "pain_point",
                    models.TextField(help_text="What problem are they facing?"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("cold_call", "Cold Call"),
                            ("referral", "Referral"),
                            ("linkedin", "LinkedIn"),
                            ("website", "Website"),
                            ("other", "Other"),
                        ],
                        default="cold_call",
                        max_length=20,
                    ),
                ),
                (
                    "value_estimate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Estimated monthly retainer (KES)",
                        max_digits=10,
                    ),
                ),
                ("first_contact_date", models.DateTimeField(auto_now_add=True)),
                ("last_interaction_date", models.DateTimeField(blank=True, null=True)),
                (
                    "next_action",
                    models.CharField(
                        blank=True, help_text="What's the next step?", max_length=200
                    ),
                ),
                ("next_action_due", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Comma-separated tags", max_length=200
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PipelineStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("order", models.IntegerField(default=0)),
                ("is_won", models.BooleanField(default=False)),
                ("is_lost", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Interaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("call", "Phone Call"),
                            ("whatsapp", "WhatsApp"),
                            ("email", "Email"),
                            ("meeting", "Meeting"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("summary", models.TextField(help_text="What was discussed?")),
                (
                    "outcome",
                    models.CharField(
                        blank=True, help_text="What was agreed?", max_length=200
                    ),
                ),
                ("duration_minutes", models.IntegerField(blank=True, null=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="crm.lead",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="lead",
            name="stage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="crm.pipelinestage"
            ),
        ),
    ]
