# Generated by Django 6.0.1 on 2026-01-19 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lead",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Lead",
                "verbose_name_plural": "Leads",
            },
        ),
        migrations.AlterModelOptions(
            name="pipelinestage",
            options={
                "ordering": ["order"],
                "verbose_name": "Pipeline Stage",
                "verbose_name_plural": "Pipeline Stages",
            },
        ),
        migrations.AlterField(
            model_name="interaction",
            name="duration_minutes",
            field=models.IntegerField(
                blank=True,
                help_text="How long did this interaction take? (helps track time spent per lead)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="interaction",
            name="interaction_type",
            field=models.CharField(
                choices=[
                    ("call", "Phone Call"),
                    ("whatsapp", "WhatsApp"),
                    ("email", "Email"),
                    ("meeting", "In-Person Meeting"),
                    ("video_call", "Video Call (Zoom/Meet)"),
                    ("other", "Other"),
                ],
                help_text="How did you communicate?",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="interaction",
            name="lead",
            field=models.ForeignKey(
                help_text="Which lead is this interaction with?",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interactions",
                to="crm.lead",
            ),
        ),
        migrations.AlterField(
            model_name="interaction",
            name="outcome",
            field=models.CharField(
                blank=True,
                help_text="What was agreed/decided? (e.g., 'Meeting booked for Friday', 'Not interested')",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="interaction",
            name="summary",
            field=models.TextField(
                help_text="REQUIRED: What was discussed? What did they say? Be specific."
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="first_contact_date",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="When you first reached out (auto-set on creation)",
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="last_interaction_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time you called/emailed/met (auto-updated when logging interaction)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="next_action",
            field=models.CharField(
                blank=True,
                help_text="What's the next step? (e.g., 'Send proposal', 'Follow-up call')",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="next_action_due",
            field=models.DateTimeField(
                blank=True,
                help_text="When should next_action happen? (used for reminders)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Internal notes, conversation summaries, anything useful",
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="pain_point",
            field=models.TextField(
                help_text="CRITICAL: What problem are they facing? Be specific. Example: 'Manually enters 50 orders daily into Excel, takes 2 hours, frequent errors'"
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="source",
            field=models.CharField(
                choices=[
                    ("cold_call", "Cold Call"),
                    ("cold_email", "Cold Email"),
                    ("referral", "Referral"),
                    ("linkedin", "LinkedIn"),
                    ("website", "Website Form"),
                    ("networking", "Networking Event"),
                    ("other", "Other"),
                ],
                default="cold_call",
                help_text="How did you find this lead?",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="stage",
            field=models.ForeignKey(
                help_text="Current stage in pipeline",
                on_delete=django.db.models.deletion.PROTECT,
                to="crm.pipelinestage",
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="tags",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated tags (e.g., 'urgent, high-value, decision-maker')",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="value_estimate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Estimated monthly retainer (KES). Used to prioritize high-value leads",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="pipelinestage",
            name="is_lost",
            field=models.BooleanField(
                default=False, help_text="True if this stage means 'we lost the lead'"
            ),
        ),
        migrations.AlterField(
            model_name="pipelinestage",
            name="is_won",
            field=models.BooleanField(
                default=False, help_text="True if this stage means 'we got the client'"
            ),
        ),
        migrations.AlterField(
            model_name="pipelinestage",
            name="name",
            field=models.CharField(
                help_text="Stage name (e.g., 'Meeting Booked')",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="pipelinestage",
            name="order",
            field=models.IntegerField(
                default=0, help_text="Display order (0=first stage, 1=second, etc.)"
            ),
        ),
    ]
